### ISSUE TITLE
introduction package and indexed_search error

### ISSUE THREAD

**Issue by pjaouen** [FriendsOfTYPO3/introduction#115]
I have a new typo3 13 LTS with introduction package on opensuse leap 15.6 (only introduction, no new pages)

error :
Indexed Search
TYPO3 ships with a ready to use search.
Oops, an error occurred! Request: 40d5a5d92d550

Fri, 18 Oct 2024 11:58:58 +0200 [ALERT] request="f5cbdf596f448" component="TYPO3.CMS.Frontend.ContentObject.Exception.ProductionExceptionHandler": Oops, an error occurred! Request: f5cbdf596f448- Exception: TypoScript object path "tt_content.list.20.indexedsearch_pi2" does not exist, in file /srv/www/htdocs/sgc/vendor/typo3/cms-fluid/Classes/ViewHelpers/CObjectViewHelper.php:147 - {"exception":"TYPO3Fluid\\Fluid\\Core\\ViewHelper\\Exception: TypoScript object path \"tt_content.list.20.indexedsearch_pi2\" does not exist in /srv/www/htdocs/sgc/vendor/typo3/cms-fluid/Classes/ViewHelpers/CObjectViewHelper.php:147\nStack trace:\n#0 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(261): TYPO3\\CMS\\Fluid\\ViewHelpers\\CObjectViewHelper->render()\n#1 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/Core/ViewHelper/ViewHelperInvoker.php(69): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->initializeArgumentsAndRender()\n#2 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/ViewHelperNode.php(125): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\ViewHelperInvoker->invoke()\n#3 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/AbstractNode.php(59): TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\ViewHelperNode->evaluate()\n#4 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/AbstractNode.php(41): TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\AbstractNode->evaluateChildNode()\n#5 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(305): TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\AbstractNode->evaluateChildNodes()\n#6 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(282): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->TYPO3Fluid\\Fluid\\Core\\ViewHelper\\{closure}()\n#7 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/ViewHelpers/SectionViewHelper.php(95): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->renderChildren()\n#8 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(261): TYPO3Fluid\\Fluid\\ViewHelpers\\SectionViewHelper->render()\n#9 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/Core/ViewHelper/ViewHelperInvoker.php(69): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->initializeArgumentsAndRender()\n#10 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/ViewHelperNode.php(125): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\ViewHelperInvoker->invoke()\n#11 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/View/AbstractTemplateView.php(241): TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\ViewHelperNode->evaluate()\n#12 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/ViewHelpers/RenderViewHelper.php(162): TYPO3Fluid\\Fluid\\View\\AbstractTemplateView->renderSection()\n#13 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(261): TYPO3Fluid\\Fluid\\ViewHelpers\\RenderViewHelper->render()\n#14 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/Core/ViewHelper/ViewHelperInvoker.php(69): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->initializeArgumentsAndRender()\n#15 /srv/www/htdocs/sgc/var/cache/code/fluid_template/layout_Default_html_99410f6af6a00821.php(409): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\ViewHelperInvoker->invoke()\n#16 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(282): layout_Default_html_99410f6af6a00821->{closure}()\n#17 /srv/www/htdocs/sgc/vendor/bk2k/bootstrap-package/Classes/ViewHelpers/FrameViewHelper.php(160): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->renderChildren()\n#18 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(261): BK2K\\BootstrapPackage\\ViewHelpers\\FrameViewHelper->render()\n#19 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/Core/ViewHelper/ViewHelperInvoker.php(69): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->initializeArgumentsAndRender()\n#20 /srv/www/htdocs/sgc/var/cache/code/fluid_template/layout_Default_html_99410f6af6a00821.php(526): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\ViewHelperInvoker->invoke()\n#21 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/View/AbstractTemplateView.php(161): layout_Default_html_99410f6af6a00821->render()\n#22 /srv/www/htdocs/sgc/vendor/typo3/cms-fluid/Classes/View/FluidViewAdapter.php(57): TYPO3Fluid\\Fluid\\View\\AbstractTemplateView->render()\n#23 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/ContentObject/FluidTemplateContentObject.php(140): TYPO3\\CMS\\Fluid\\View\\FluidViewAdapter->render()\n#24 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectRenderer.php(654): TYPO3\\CMS\\Frontend\\ContentObject\\FluidTemplateContentObject->render()\n#25 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectRenderer.php(601): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render()\n#26 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/ContentObject/CaseContentObject.php(45): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle()\n#27 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectRenderer.php(654): TYPO3\\CMS\\Frontend\\ContentObject\\CaseContentObject->render()\n#28 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectRenderer.php(601): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render()\n#29 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/ContentObject/ContentContentObject.php(116): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle()\n#30 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectRenderer.php(654): TYPO3\\CMS\\Frontend\\ContentObject\\ContentContentObject->render()\n#31 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectRenderer.php(601): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render()\n#32 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectRenderer.php(570): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle()\n#33 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectRenderer.php(550): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSeparated()\n#34 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectArrayContentObject.php(43): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGet()\n#35 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectRenderer.php(654): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectArrayContentObject->render()\n#36 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectRenderer.php(601): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render()\n#37 /srv/www/htdocs/sgc/vendor/typo3/cms-fluid/Classes/ViewHelpers/CObjectViewHelper.php(177): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle()\n#38 /srv/www/htdocs/sgc/vendor/typo3/cms-fluid/Classes/ViewHelpers/CObjectViewHelper.php(160): TYPO3\\CMS\\Fluid\\ViewHelpers\\CObjectViewHelper::renderContentObject()\n#39 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(261): TYPO3\\CMS\\Fluid\\ViewHelpers\\CObjectViewHelper->render()\n#40 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/Core/ViewHelper/ViewHelperInvoker.php(69): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->initializeArgumentsAndRender()\n#41 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/ViewHelperNode.php(125): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\ViewHelperInvoker->invoke()\n#42 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/AbstractNode.php(59): TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\ViewHelperNode->evaluate()\n#43 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/AbstractNode.php(41): TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\AbstractNode->evaluateChildNode()\n#44 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(305): TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\AbstractNode->evaluateChildNodes()\n#45 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(282): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->TYPO3Fluid\\Fluid\\Core\\ViewHelper\\{closure}()\n#46 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/ViewHelpers/SectionViewHelper.php(95): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->renderChildren()\n#47 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(261): TYPO3Fluid\\Fluid\\ViewHelpers\\SectionViewHelper->render()\n#48 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/Core/ViewHelper/ViewHelperInvoker.php(69): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->initializeArgumentsAndRender()\n#49 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/ViewHelperNode.php(125): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\ViewHelperInvoker->invoke()\n#50 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/View/AbstractTemplateView.php(241): TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\ViewHelperNode->evaluate()\n#51 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/ViewHelpers/RenderViewHelper.php(162): TYPO3Fluid\\Fluid\\View\\AbstractTemplateView->renderSection()\n#52 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(261): TYPO3Fluid\\Fluid\\ViewHelpers\\RenderViewHelper->render()\n#53 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/Core/ViewHelper/ViewHelperInvoker.php(69): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->initializeArgumentsAndRender()\n#54 /srv/www/htdocs/sgc/var/cache/code/fluid_template/layout_Default_html_9067fe68aaf1f63c.php(216): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\
ViewHelperInvoker->invoke()\n#55 /srv/www/htdocs/sgc/vendor/typo3fluid/fluid/src/View/AbstractTemplateView.php(161): layout_Default_html_9067fe68aaf1f63c->render()\n#56 /srv/www/htdocs/sgc/vendor/typo3/cms-fluid/Classes/View/FluidViewAdapter.php(57): TYPO3Fluid\\Fluid\\View\\AbstractTemplateView->render()\n#57 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/ContentObject/FluidTemplateContentObject.php(140): TYPO3\\CMS\\Fluid\\View\\FluidViewAdapter->render()\n#58 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectRenderer.php(654): TYPO3\\CMS\\Frontend\\ContentObject\\FluidTemplateContentObject->render()\n#59 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectRenderer.php(601): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render()\n#60 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectRenderer.php(570): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle()\n#61 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectRenderer.php(550): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSeparated()\n#62 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/Http/RequestHandler.php(227): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGet()\n#63 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/Http/RequestHandler.php(196): TYPO3\\CMS\\Frontend\\Http\\RequestHandler->generatePageBodyContent()\n#64 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/Http/RequestHandler.php(137): TYPO3\\CMS\\Frontend\\Http\\RequestHandler->generatePageContent()\n#65 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Middleware/ResponsePropagation.php(34): TYPO3\\CMS\\Frontend\\Http\\RequestHandler->handle()\n#66 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Core\\Middleware\\ResponsePropagation->process()\n#67 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/Middleware/OutputCompression.php(44): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#68 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Frontend\\Middleware\\OutputCompression->process()\n#69 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/Middleware/ContentSecurityPolicyHeaders.php(58): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#70 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Frontend\\Middleware\\ContentSecurityPolicyHeaders->process()\n#71 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/Middleware/CacheTimeout.php(34): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#72 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Frontend\\Middleware\\CacheTimeout->process()\n#73 /srv/www/htdocs/sgc/vendor/typo3/cms-adminpanel/Classes/Middleware/AdminPanelRenderer.php(41): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#74 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Adminpanel\\Middleware\\AdminPanelRenderer->process()\n#75 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/Middleware/ContentLengthResponseHeader.php(41): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#76 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Frontend\\Middleware\\ContentLengthResponseHeader->process()\n#77 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/Middleware/ShortcutAndMountPointRedirect.php(94): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#78 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Frontend\\Middleware\\ShortcutAndMountPointRedirect->process()\n#79 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/Middleware/PrepareTypoScriptFrontendRendering.php(180): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#80 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Frontend\\Middleware\\PrepareTypoScriptFrontendRendering->process()\n#81 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/Middleware/TypoScriptFrontendInitialization.php(126): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#82 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Frontend\\Middleware\\TypoScriptFrontendInitialization->process()\n#83 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/Middleware/PreviewSimulator.php(91): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#84 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Frontend\\Middleware\\PreviewSimulator->process()\n#85 /srv/www/htdocs/sgc/vendor/typo3/cms-adminpanel/Classes/Middleware/SqlLogging.php(53): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#86 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Adminpanel\\Middleware\\SqlLogging->process()\n#87 /srv/www/htdocs/sgc/vendor/typo3/cms-workspaces/Classes/Middleware/WorkspacePreviewPermissions.php(44): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#88 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Workspaces\\Middleware\\WorkspacePreviewPermissions->process()\n#89 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/Middleware/PageArgumentValidator.php(104): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#90 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Frontend\\Middleware\\PageArgumentValidator->process()\n#91 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/Middleware/PageResolver.php(101): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#92 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Frontend\\Middleware\\PageResolver->process()\n#93 /srv/www/htdocs/sgc/vendor/typo3/cms-workspaces/Classes/Middleware/WorkspacePreview.php(126): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#94 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Workspaces\\Middleware\\WorkspacePreview->process()\n#95 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/Middleware/StaticRouteResolver.php(71): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#96 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Frontend\\Middleware\\StaticRouteResolver->process()\n#97 /srv/www/htdocs/sgc/vendor/typo3/cms-adminpanel/Classes/Middleware/AdminPanelInitiator.php(51): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#98 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Adminpanel\\Middleware\\AdminPanelInitiator->process()\n#99 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/Middleware/ContentSecurityPolicyReporter.php(42): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#100 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Frontend\\Middleware\\ContentSecurityPolicyReporter->process()\n#101 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/Middleware/SiteBaseRedirectResolver.php(90): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#102 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Frontend\\Middleware\\SiteBaseRedirectResolver->process()\n#103 /srv/www/htdocs/sgc/vendor/typo3/cms-redirects/Classes/Http/Middleware/RedirectHandler.php(68): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#104 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Redirects\\Http\\Middleware\\RedirectHandler->process()\n#105 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/Middleware/FrontendUserAuthenticator.php(76): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#106 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Frontend\\Middleware\\FrontendUserAuthenticator->process()\n#107 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/Middleware/BackendUserAuthenticator.php(82): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#108 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Frontend\\Middleware\\BackendUserAuthenticator->process()\n#109 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Middleware/RequestTokenMiddleware.php(71): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#110 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Core\\Middleware\\RequestTokenMiddleware->process()\n#111 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/Middleware/MaintenanceMode.php(51): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#112 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Frontend\\Middleware\\MaintenanceMode->process()\n#113 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/Middleware/EidHandler.php(48): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#114 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Frontend\\Middleware\\EidHandler->process()\n#115 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/Middleware/SiteResolver.php(53): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#116 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Frontend\\
Middleware\\SiteResolver->process()\n#117 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Middleware/CacheDataCollectorAttribute.php(53): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#118 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Core\\Middleware\\CacheDataCollectorAttribute->process()\n#119 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Middleware/NormalizedParamsAttribute.php(44): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#120 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Core\\Middleware\\NormalizedParamsAttribute->process()\n#121 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/Middleware/TimeTrackerInitialization.php(49): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#122 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Frontend\\Middleware\\TimeTrackerInitialization->process()\n#123 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(70): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#124 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/AbstractApplication.php(83): TYPO3\\CMS\\Core\\Http\\MiddlewareDispatcher->handle()\n#125 /srv/www/htdocs/sgc/vendor/typo3/cms-frontend/Classes/Http/Application.php(49): TYPO3\\CMS\\Core\\Http\\AbstractApplication->handle()\n#126 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/RequestHandler.php(42): TYPO3\\CMS\\Frontend\\Http\\Application->handle()\n#127 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Middleware/ResponsePropagation.php(34): TYPO3\\CMS\\Core\\Http\\RequestHandler->handle()\n#128 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Core\\Middleware\\ResponsePropagation->process()\n#129 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Middleware/NormalizedParamsAttribute.php(44): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#130 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Core\\Middleware\\NormalizedParamsAttribute->process()\n#131 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Middleware/VerifyHostHeader.php(55): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#132 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Core\\Middleware\\VerifyHostHeader->process()\n#133 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(70): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()\n#134 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/AbstractApplication.php(83): TYPO3\\CMS\\Core\\Http\\MiddlewareDispatcher->handle()\n#135 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/Application.php(44): TYPO3\\CMS\\Core\\Http\\AbstractApplication->handle()\n#136 /srv/www/htdocs/sgc/vendor/typo3/cms-core/Classes/Http/AbstractApplication.php(95): TYPO3\\CMS\\Core\\Http\\Application->handle()\n#137 /srv/www/htdocs/sgc/public/index.php(20): TYPO3\\CMS\\Core\\Http\\AbstractApplication->run()\n#138 /srv/www/htdocs/sgc/public/index.php(21): {closure}()\n#139 {main}","code":"2024101811585835c9c45f","requestId":{"long":"f5cbdf596f448ac923ef50c1173e8f52243f0eba","short":"f5cbdf596f448","microtime":1729245538235410,"nonce":{"value":"5PfIVwMec7fm_hvGzSz1OJuK2BqxeFEcoNwOj8Ngcytf6Sc62v64KQ"}}}

**Comment by garvinhicking** [comment]
This is actually a bug of EXT:bootstrap_package. I've made a PR for this:

https://github.com/benjaminkott/bootstrap_package/pull/1537

Once that is merged and a new release is made, it would need to be included as a dependency of this package.
